sudo: required
services:
- docker
os:
- linux
notifications:
  email: false
branches:
- chore/deployment
env:
  global:
  - DOCKER_IMAGE_NAME="pi-engine"
  - DOCKER_HUB_ORG="trastanechora"
before_script:
- sudo snap install kubectl --classic
- sudo cp /etc/kubernetes/admin.conf $HOME/
- sudo chown $(id -u):$(id -g) $HOME/admin.conf
- export KUBECONFIG=$HOME/admin.conf
- sudo kubectl version
- sudo kubectl version --client
- sudo docker --version
- sudo docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"