sudo: required
services:
- docker
os:
- linux
notifications:
  email: false
branches:
- chore/deployment
env:
  global:
  - DOCKER_IMAGE_NAME="pi-engine"
  - DOCKER_HUB_ORG="trastanechora"
before_script:
- snap install kubectl --classic
- kubectl version
- kubectl version --client
- docker --version
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"