sudo: required
services:
- docker
os:
- linux
notifications:
  email: false
branches:
- chore/deployment
env:
  global:
  - DOCKER_IMAGE_NAME="pi-engine"
	- DOCKER_HUB_ORG="trastanechora"
before_script:
# - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
# - sudo chmod +x ./kubectl
# - sudo mv kubectl /usr/local/bin/
# - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.4.0/minikube-linux-amd64
# - chmod +x minikube
# - sudo mv minikube /usr/local/bin/
# - sudo mkdir -p $HOME/.kube $HOME/.minikube
# - sudo minikube start --vm-driver=none --kubernetes-version=v1.16.0
# - sudo kubectl version
# - sudo docker --version
- sudo docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"