sudo: required
services:
- docker
os:
- linux
language: go
notifications:
  email: false
branches:
- chore/deployment
env:
  global:
  - DOCKER_IMAGE_NAME="pi-engine"
  - DOCKER_HUB_ORG="trastanechora"
before_script:
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.4.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- mkdir -p $HOME/.kube $HOME/.minikube
script:
- touch $HOME/.kube/config
- sudo minikube start --vm-driver=none --kubernetes-version=v1.16.0
- "sudo chown -R travis: /home/travis/.minikube/"
- kubectl cluster-info
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lcomponent=kube-addon-manager -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to be available"; kubectl get pods --all-namespaces; done
- kubectl apply -f https://k8s.io/examples/service/load-balancer-example.yaml
- kubectl get deployments hello-world
- kubectl describe deployments hello-world
- kubectl get replicasets
- kubectl describe replicasets
- kubectl expose deployment hello-world --type=LoadBalancer --name=my-service
- kubectl get services my-service
- kubectl describe services my-service
- kubectl get pods --output=wide
- kubectl describe services my-service